# Generated by Django 5.1.7 on 2025-04-01 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectReport',
        ),
    ]
