# Generated by Django 5.1.7 on 2025-03-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='dependency',
            field=models.ManyToManyField(blank=True, related_name='dependent_tasks', to='tasks.task'),
        ),
    ]
